# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5a1354b25ad45ae4ba812d1312cb8db1cd59e8b252f7a8fe96763e3a000ae6637160a2987729039d5a58d71520ffe8898acadafbf753afe4aa45dfea25518b

test:
  secret_key_base: ea04423281efff2d892084c33095a1f4d175201cfc099d7ccecc525b95d218dd3fa8c4197f7fe75e8369c7290ceecfadc15a7aa164a99ec32485c2f0a87b0c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
